openapi: "3.0.0"
info:
  title: "URL shortner API backend"
  version: "1.0.0"
  description: An over-engineered API backend for a simple URL shortner web application.
  servers:
    - url: http://localhost:3000

components:
  responses:
    InternalServerError:
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          example:
            message: "Something went wrong! Please try again later."

paths:
  /api/test:
    get:
      summary: Returns a test message
      responses:
        "200":
          description: A JSON object with the success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: A text message

  /api/user/signup:
    post:
      summary: Add new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fullName
                - email
                - password
              properties:
                fullName:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  format: password
                  example: mysecret123
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  fullName:
                    type: string
              example:
                message: User created
                email: jane@email.com
                fullName: Jane Doe
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Full name and email are required
        "401":
          description: Unauthorized. Email or password was incorrect
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Invaid/Wrong password. Please Try again
        "409":
          description: Conflicting data. Data already exists in the database.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      email:
                        type: string
              example:
                message: Email already exists. Try again with another email id.
                data:
                  mame: John Doe
                  email: test@email.com
        "500":
          $ref: "#/components/responses/InternalServerError"

  /api/user/login:
    post:
      summary: Login existing user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  format: password
                  example: mysecret123
      responses:
        "200":
          description: User logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  email:
                    type: string
                  fullName:
                    type: string
                  userid:
                    type: string
              example:
                message: User created
                email: jane@email.com
                fullName: Jane Doe
        "500":
          $ref: "#/components/responses/InternalServerError"
